export const Person = [
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    firstName: 'John 2',
    lastname: 'John weak 2',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
];
