export const Person = [
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 1,
    firstName: 'John',
    lastname: 'John weak',
    age: 30,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
  {
    id: 2,
    firstName: 'depdep',
    lastname: 'John weak',
    age: 31,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'Non active',
  },
  {
    id: 3,
    firstName: 'cecep',
    lastname: 'John weak',
    age: 32,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'In Production',
  },
  {
    id: 4,
    firstName: 'Gourgoe',
    lastname: 'John weak',
    age: 34,
    visits: 30,
    progress: 10,
    createdAt: 23924234,
    status: 'active',
  },
];
